---
- hosts: all
  sudo: true
  vars:
      document_root: /vagrant
  tasks:
      - name: Install stuff from Aptitude
        apt: name={{ item }} state=installed
        with_items:
          - git
          - tig
      - name: Install SSH key
        authorized_key: 
            user=vagrant 
            path=/home/vagrant/.ssh/authorized_keys 
            state=present
            key="{{ lookup('file', 'id_rsa_virtualcluster.pub') }}"
      - name: Set up hosts files on the nodes, for easier SSH:ing between them
        lineinfile:
          dest=/etc/hosts
          insertafter=^127\.0\.0\.1
          line={{ item }}
          state=present
        with_items:
          - '10.2.2.2\ master'
          - '10.2.2.4\ slave1'
          - '10.2.2.6\ slave2'
